print("Hello from feature A!")
print("This is a temporary change.")
print("Learning Git and GitHub!")
print("This change is on the feature branch.")
print("I am practicing Git branches.")
print("Practicing remote branches.")